// <auto-generated />
using System;
using Brewfolio.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Brewfolio.Infrastructure.Persistence.Migrations;

[DbContext(typeof(BrewfolioDbContext))]
[Migration("20260904120902_CompleteCoffeeBeanProfile")]
partial class _20260904120902_CompleteCoffeeBeanProfile
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "11.0.0-preview.7.26381.103")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Brewfolio.Domain.CoffeeBeans.CoffeeBean", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("Description")
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("nvarchar(120)");

                b.Property<string>("Origin")
                    .HasMaxLength(240)
                    .HasColumnType("nvarchar(240)");

                b.Property<string>("ProductUrl")
                    .HasMaxLength(2048)
                    .HasColumnType("nvarchar(2048)");

                b.Property<string>("RoastLevel")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<string>("Roaster")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("nvarchar(120)");

                b.Property<DateTimeOffset>("UpdatedAt")
                    .HasColumnType("datetimeoffset");

                b.HasKey("Id");

                b.HasIndex("CreatedAt");

                b.HasIndex("Roaster", "Name");

                b.ToTable("CoffeeBeans");
            });
#pragma warning restore 612, 618
    }
}
